name: Latest YouTube Videos

on:
  schedule:
    - cron: "2-59/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: youtube-feed
  cancel-in-progress: true

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update README with latest YouTube videos
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "YOUTUBE"             # matches README markers
          readme_path: "README.md"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCLHIBQeFQIxmRveVAjLvlbQ"
          max_post_count: "6"
          date_format: "mmm d, yyyy"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          # maxresdefault is not guaranteed; hqdefault is reliable + https
          template: '<table><tr><td><a href="$url"><img width="140px" src="https://img.youtube.com/vi/$videoId/hqdefault.jpg"></a></td><td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
